[binaries]
c = 'aarch64-linux-gnu-gcc'
cpp = 'aarch64-linux-gnu-g++'
ar = 'aarch64-linux-gnu-ar'
strip = 'aarch64-linux-gnu-strip'
pkg-config = ['env', 'PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig', 'pkg-config']

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
needs_exe_wrapper = true
# Bachata host runtime does not ship libxcb-xfixes.so.0. Static-link it into
# libvulkan_freedreno.so so the ICD can dlopen against the stock host rootfs.
c_link_args = ['-Wl,-Bstatic', '-lxcb-xfixes', '-Wl,-Bdynamic']
cpp_link_args = ['-Wl,-Bstatic', '-lxcb-xfixes', '-Wl,-Bdynamic']
